apiVersion: apps/v1beta1
kind: Deployment
metadata:
  initializers:
    pending:
      - name: volume.kisc.kubernetes.io
      - name: init-container.kisc.kubernetes.io
    labels:
      app: example
    name: example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example
      name: example
    spec:
      containers:
        - name: example
          image: example
